#!/usr/bin/env python3
"""Generate src/lib/han-fold.ts: a per-character traditional→simplified table from ICU's
Hant-Hans transform (icu4c's uconv), keeping only 1:1 mappings.

Each record is written as `<codepoint-hex>\t<char>` so the mapping is recovered by INDEX, not
by line position — uconv drops or substitutes some unassigned code points, which silently
shifted a positional zip (that produced 見 -> 蜗)."""
import subprocess, sys

UCONV = "/opt/homebrew/opt/icu4c/bin/uconv"
RANGES = [(0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF)]

codes = [c for lo, hi in RANGES for c in range(lo, hi + 1)]
src = "".join(f"{c:x}\t{chr(c)}\n" for c in codes)
out = subprocess.run([UCONV, "-x", "Hant-Hans"], input=src, capture_output=True, text=True)
if out.returncode != 0:
    sys.exit(f"uconv failed: {out.stderr}")

pairs, dropped, non11 = {}, 0, 0
for line in out.stdout.split("\n"):
    if not line:
        continue
    head, _, conv = line.partition("\t")
    try:
        code = int(head, 16)
    except ValueError:
        sys.exit(f"unparsable record: {line!r}")
    ch = chr(code)
    if conv == ch:
        continue
    if len(conv) != 1:
        non11 += 1
        continue
    pairs[ch] = conv
seen = sum(1 for line in out.stdout.split("\n") if line)
dropped = len(codes) - seen

trad = "".join(pairs.keys())
simp = "".join(pairs.values())
print(f"pairs: {len(pairs)}  non-1:1 skipped: {non11}  records lost by uconv: {dropped}", file=sys.stderr)

ok = True
for a, b in [("見", "见"), ("憶", "忆"), ("個", "个"), ("兩", "两"), ("過", "过"),
             ("髮", "发"), ("陌", None), ("人", None), ("再", None), ("這", "这"),
             ("樣", "样"), ("黃", "黄"), ("時", "时")]:
    got = pairs.get(a)
    good = got == b
    ok &= good
    print(f"  {a} -> {got!r} (want {b!r}) {'OK' if good else 'MISMATCH'}", file=sys.stderr)
if not ok:
    sys.exit("table failed its known-answer checks; nothing written")

header = '''// Traditional → simplified Han folding, for SEARCH MATCHING only. Nothing here touches a
// stored or displayed string.
//
// WHY: the same song sits in this store under both scripts, because Spotify hands the same
// title out both ways depending on which release you reached it through — verified against the
// live store on 2026-08-22, where "Ada Zhuang" has BOTH `两个人的回忆一个人过` (in 1 playlist)
// and `兩個人的回憶一個人過` (in 2), and the title Rem searched — `再见只是陌生人` — was in his
// library only as `再見只是陌生人`. A substring match over the raw titles finds neither from the
// other, so a song he owns reads as missing.
//
// DIRECTION: traditional → simplified, because that direction is very nearly 1:1. The reverse
// is one-to-many (发 → 發/髮, 干 → 幹/乾/干) and cannot be a character table at all.
//
// SOURCE: ICU's `Hant-Hans` transform (icu4c's `uconv -x Hant-Hans`), applied per character
// over U+3400-4DBF, U+4E00-9FFF and U+F900-FAFF, keeping only characters whose conversion is
// exactly one character. GENERATED by scripts/gen-han-fold.py — do not hand-edit; that script
// carries the known-answer checks and refuses to write a table that fails them.
//
// The two strings are positional — the i-th CODE POINT of TRAD folds to the i-th of SIMP.
// Paired strings rather than an object literal because it is a third of the bytes.
'''

with open("/Users/remtbkv/projects/lazyboy/src/lib/han-fold.ts", "w") as f:
    f.write(header)
    f.write(f'\nconst TRAD =\n  "{trad}";\nconst SIMP =\n  "{simp}";\n')
    f.write('''
// Built by CODE POINT, not by string index: a handful of simplified variants live outside
// the BMP (㠣 -> 𫵷), so TRAD[i]/SIMP[i] would desynchronise at the first one and silently
// map the rest of the table to the wrong characters (見 -> 蜗, caught by the tests).
const TABLE = new Map<string, string>();
{
  const trad = [...TRAD];
  const simp = [...SIMP];
  for (let i = 0; i < trad.length; i++) TABLE.set(trad[i], simp[i]);
}

// Deliberately a plain range test, not a /u property escape: this runs on every keystroke and
// over every indexed name, and all it has to answer is "could anything in here fold".
const HAS_HAN = /[\\u3400-\\u9fff\\uf900-\\ufaff]/;

/** Fold a string to its simplified-Han, lower-cased match form. Text with no Han passes
 *  through as a plain lower-case, so a Latin-only library pays one regex test per string. */
export function hanFold(s: string): string {
  const lower = s.toLowerCase();
  if (!HAS_HAN.test(lower)) return lower;
  let out = "";
  for (const ch of lower) out += TABLE.get(ch) ?? ch;
  return out;
}
''')
print("wrote src/lib/han-fold.ts", file=sys.stderr)
